apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
# Core Read
- apiGroups: [""]
  resources: ["configmaps","namespaces"]
  verbs: ["get","watch","list"]

# ConfigMap Write
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update","create","delete","patch"]

# CRD Read
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","watch"]

# Framework: admission webhook configuration management.
- apiGroups: ["admissionregistration.k8s.io/v1", "admissionregistration.k8s.io/v1beta1"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["create", "patch"]

# Events  
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]


# Kopf
- apiGroups: ["kopf.dev"]
  resources: ["clusterkopfpeerings"]
  verbs: ["list", "watch", "patch", "get"]

# Custom Resource Read
- apiGroups: ["xlscsde.nhs.uk"]
  resources: ["configmaptransforms"]
  verbs: ["get", "watch", "list", "patch"]